# Generated by Django 4.2.1 on 2023-06-07 09:06

import autoslug.fields
import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Govno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=253, verbose_name='Доп инфо')),
                ('birth', models.DateField(default=datetime.datetime.today)),
                ('position', models.CharField(default='неизвестно', max_length=253)),
                ('department', models.CharField(default='неизвестно', max_length=250)),
                ('resume', models.TextField(default='')),
                ('dop_info', models.TextField(blank=True, default='', null=True)),
                ('created_date', models.DateField(verbose_name='Дата события')),
                ('criminal_record', models.BooleanField(default=False)),
                ('years', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Информация',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('description', models.TextField(default='')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('order_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='newsImage/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('overview', ckeditor.fields.RichTextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/detail/')),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newsImage', to='app.news')),
            ],
            options={
                'verbose_name': 'Галерея Новости',
                'verbose_name_plural': 'Галерея Новостей',
            },
        ),
        migrations.CreateModel(
            name='GovnoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='govno/detail/')),
                ('govno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='govnoImage', to='app.news')),
            ],
            options={
                'verbose_name': 'Галерея Дополнительной информации',
                'verbose_name_plural': 'Галерея Дополнительной информации',
            },
        ),
    ]
