# Generated by Django 4.2.1 on 2023-06-05 06:01

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_category_options_remove_category_news_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Govno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=253)),
                ('birth', models.CharField(default='', max_length=20)),
                ('position', models.CharField(default='неизвестно', max_length=253)),
                ('department', models.CharField(default='неизвестно', max_length=250)),
                ('resume', models.TextField(default='')),
                ('dop_info', models.TextField(blank=True, default='', null=True)),
                ('created_date', models.DateField(verbose_name='Дата события')),
                ('criminal_record', models.BooleanField(default=False)),
                ('years', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Информация',
            },
        ),
    ]
