# Generated by Django 4.2.1 on 2023-06-05 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_govno'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovnoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='govno/detail/')),
                ('govno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='govnoImage', to='app.news')),
            ],
            options={
                'verbose_name': 'Галерея Дополнительной информации',
                'verbose_name_plural': 'Галерея Дополнительной информации',
            },
        ),
    ]
