# Generated by Django 4.2.1 on 2023-06-09 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_post_options_alter_govno_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='newsImage/'),
        ),
        migrations.AddField(
            model_name='post',
            name='top_news',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='govno',
            name='name',
            field=models.CharField(default='', max_length=253, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='govnoimage',
            name='govno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='govnoImage', to='app.govno'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newsImage', to='app.post'),
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
