# Generated by Django 4.2.1 on 2023-06-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_govno_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='govno',
            name='name',
            field=models.CharField(default='', max_length=253, verbose_name='Доп инфо'),
        ),
    ]
