# Generated by Django 4.2.1 on 2023-06-05 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_govno_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='news',
            new_name='category',
        ),
    ]
