# Generated by Django 4.2.1 on 2023-06-09 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_department_alter_press_release_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='press_release',
            old_name='category',
            new_name='departments',
        ),
    ]
