# Generated by Django 4.2.1 on 2023-06-12 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_newssngimage_news_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страны СНГ', 'verbose_name_plural': 'Страны СНГ'},
        ),
    ]
