# Generated by Django 4.2.1 on 2023-06-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_anonymoususercount'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoususercount',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
    ]
