# Generated by Django 4.2.1 on 2023-06-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_anonymoususercount_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymoususercount',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
