# Generated by Django 4.2.1 on 2023-06-13 11:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_anonymoususercount_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='govno',
            name='dop_info',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='govno',
            name='resume',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
