# Generated by Django 4.2.1 on 2023-06-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_newsimage_image_newsimage_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsimage',
            name='images',
        ),
        migrations.AddField(
            model_name='newsimage',
            name='image',
            field=models.ImageField(default='', upload_to='news/detail/'),
            preserve_default=False,
        ),
    ]
