# Generated by Django 4.2.1 on 2023-06-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_newsimage_images_newsimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='govno',
            name='image',
            field=models.ImageField(default='', upload_to='avatars/', verbose_name='Фотографии'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newssng',
            name='image',
            field=models.ImageField(default='', upload_to='pressRelease/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='newsImage/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='press_release',
            name='image',
            field=models.ImageField(default='', upload_to='pressRelease/'),
            preserve_default=False,
        ),
    ]
