# Generated by Django 4.2.1 on 2023-06-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_govno_image_alter_newssng_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.ImageField(default='', upload_to='departments/logo/'),
            preserve_default=False,
        ),
    ]
