# Generated by Django 4.2.1 on 2023-06-15 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_post_title_ky_post_title_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_ru',
        ),
    ]
