# Generated by Django 4.2.1 on 2023-06-16 11:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_post_title_ky_post_title_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='overview_ky',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='overview_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
