# Generated by Django 4.2.1 on 2023-06-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_post_overview_ky_post_overview_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description_ky',
            field=models.TextField(default='', max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='description_ru',
            field=models.TextField(default='', max_length=180, null=True),
        ),
    ]
