# Generated by Django 4.2.1 on 2023-06-16 11:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_post_description_ky_post_description_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Наименование категории'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(default='', max_length=180, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description_ky',
            field=models.TextField(default='', max_length=180, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description_ru',
            field=models.TextField(default='', max_length=180, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='overview',
            field=ckeditor.fields.RichTextField(verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='overview_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='overview_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=225, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_ky',
            field=models.CharField(max_length=225, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=225, null=True, verbose_name='Наименование'),
        ),
    ]
