# Generated by Django 4.2.1 on 2023-06-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_category_title_alter_post_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='newsImage/', verbose_name='Главная фотография'),
        ),
        migrations.AlterField(
            model_name='post',
            name='top_news',
            field=models.BooleanField(default=False, verbose_name='Топ новость'),
        ),
    ]
