# Generated by Django 4.2.1 on 2023-06-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_post_image_alter_post_top_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Наименование категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Наименование категории'),
        ),
    ]
