# Generated by Django 4.2.1 on 2023-06-16 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_category_title_ky_category_title_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_ru',
        ),
        migrations.AddField(
            model_name='post',
            name='category_ky',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='category_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category'),
        ),
    ]
