# Generated by Django 4.2.1 on 2023-06-16 11:34

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_category_title_ky_remove_category_title_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='govno',
            name='criminal_record_ky',
            field=models.BooleanField(default=False, verbose_name='Судимость'),
        ),
        migrations.AddField(
            model_name='govno',
            name='criminal_record_ru',
            field=models.BooleanField(default=False, verbose_name='Судимость'),
        ),
        migrations.AddField(
            model_name='govno',
            name='department_ky',
            field=models.CharField(default='неизвестно', max_length=250, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='govno',
            name='department_ru',
            field=models.CharField(default='неизвестно', max_length=250, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='govno',
            name='dop_info_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AddField(
            model_name='govno',
            name='dop_info_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AddField(
            model_name='govno',
            name='name_ky',
            field=models.CharField(default='', max_length=253, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='govno',
            name='name_ru',
            field=models.CharField(default='', max_length=253, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='govno',
            name='position_ky',
            field=models.CharField(default='неизвестно', max_length=253, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='govno',
            name='position_ru',
            field=models.CharField(default='неизвестно', max_length=253, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='govno',
            name='resume_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Основная деятесльность'),
        ),
        migrations.AddField(
            model_name='govno',
            name='resume_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Основная деятесльность'),
        ),
        migrations.AddField(
            model_name='govno',
            name='years_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Годы судимости'),
        ),
        migrations.AddField(
            model_name='govno',
            name='years_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Годы судимости'),
        ),
        migrations.AddField(
            model_name='newssng',
            name='description_ky',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='newssng',
            name='description_ru',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='newssng',
            name='overview_ky',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='newssng',
            name='overview_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='newssng',
            name='sng_ky',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.country'),
        ),
        migrations.AddField(
            model_name='newssng',
            name='sng_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.country'),
        ),
        migrations.AddField(
            model_name='newssng',
            name='title_ky',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='newssng',
            name='title_ru',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='press_release',
            name='departments_ky',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.department'),
        ),
        migrations.AddField(
            model_name='press_release',
            name='departments_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.department'),
        ),
        migrations.AddField(
            model_name='press_release',
            name='description_ky',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='press_release',
            name='description_ru',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='press_release',
            name='overview_ky',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='press_release',
            name='overview_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='press_release',
            name='title_ky',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='press_release',
            name='title_ru',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
