# Generated by Django 4.2.1 on 2023-06-16 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_govno_criminal_record_ky_govno_criminal_record_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='govno',
            name='criminal_record_ky',
        ),
        migrations.RemoveField(
            model_name='govno',
            name='criminal_record_ru',
        ),
    ]
