# Generated by Django 4.2.1 on 2023-06-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_remove_newssng_title_ky_remove_newssng_title_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssng',
            name='title_ky',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='newssng',
            name='title_ru',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
