# Generated by Django 4.2.1 on 2023-06-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_newssng_title_ky_newssng_title_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssng',
            name='title',
            field=models.CharField(max_length=225, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='newssng',
            name='title_ky',
            field=models.CharField(max_length=225, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='newssng',
            name='title_ru',
            field=models.CharField(max_length=225, null=True, verbose_name='Наименование'),
        ),
    ]
