# Generated by Django 4.2.1 on 2023-06-19 05:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_newssng_title_alter_newssng_title_ky_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssng',
            name='overview',
            field=ckeditor.fields.RichTextField(verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='newssng',
            name='overview_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='newssng',
            name='overview_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='press_release',
            name='overview',
            field=ckeditor.fields.RichTextField(verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='press_release',
            name='overview_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='press_release',
            name='overview_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Полное описание'),
        ),
    ]
