# Generated by Django 4.2.1 on 2023-06-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_newssng_overview_alter_newssng_overview_ky_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newssng',
            name='sng_ky',
        ),
        migrations.RemoveField(
            model_name='newssng',
            name='sng_ru',
        ),
        migrations.AddField(
            model_name='country',
            name='title_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='country',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Наименование'),
        ),
    ]
