# Generated by Django 4.2.1 on 2023-06-19 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_newssng_sng_ky_remove_newssng_sng_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='govno',
            name='name_ky',
        ),
        migrations.RemoveField(
            model_name='govno',
            name='name_ru',
        ),
    ]
