# Generated by Django 4.2.1 on 2023-06-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_press_release_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category_ky',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category_ru',
        ),
        migrations.AddField(
            model_name='category',
            name='title_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Наименование категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Наименование категории'),
        ),
    ]
