# Generated by Django 4.2.1 on 2023-06-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_remove_post_category_ky_remove_post_category_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='press_release',
            name='departments_ky',
        ),
        migrations.RemoveField(
            model_name='press_release',
            name='departments_ru',
        ),
        migrations.AddField(
            model_name='department',
            name='title_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='department',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Наименование'),
        ),
    ]
