# Generated by Django 4.2.1 on 2023-06-19 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_remove_press_release_departments_ky_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press_release',
            name='departments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.department', verbose_name='Министерство/учреждениеы'),
        ),
    ]
