# Generated by Django 4.2.1 on 2023-06-19 10:12

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_press_release_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photos',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newssng',
            name='created_date',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='newssng',
            name='description',
            field=models.TextField(default='', verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='newssng',
            name='description_ky',
            field=models.TextField(default='', null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='newssng',
            name='description_ru',
            field=models.TextField(default='', null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='newssng',
            name='image',
            field=models.ImageField(upload_to='pressRelease/', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='newssng',
            name='sng',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='newssng',
            name='top_news',
            field=models.BooleanField(default=False, verbose_name='Входит в топ-новостей'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Категории новостей'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='newsImage/', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='post',
            name='top_news',
            field=models.BooleanField(default=False, verbose_name='Входит в топ-новостей'),
        ),
        migrations.AlterField(
            model_name='press_release',
            name='created_date',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='press_release',
            name='description',
            field=models.TextField(default='', verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='press_release',
            name='description_ky',
            field=models.TextField(default='', null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='press_release',
            name='description_ru',
            field=models.TextField(default='', null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='press_release',
            name='image',
            field=models.ImageField(upload_to='pressRelease/', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='press_release',
            name='top_news',
            field=models.BooleanField(default=False, verbose_name='Входит в топ-новостей'),
        ),
    ]
