# Generated by Django 4.2.1 on 2023-06-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_post_photos_alter_newssng_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=models.FileField(upload_to='news/detail/'),
        ),
    ]
