# Generated by Django 4.2.1 on 2023-06-19 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_newsimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photos',
        ),
    ]
