# Generated by Django 4.2.1 on 2023-06-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_alter_govnoimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='govno',
            name='surname',
            field=models.CharField(default='', max_length=253, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='govno',
            name='name',
            field=models.CharField(default='', max_length=253, verbose_name='Имя'),
        ),
    ]
